name: deep test

on:
  push:
  workflow_dispatch:
    inputs:
      package:
        description: "Package name"
        required: true
      version:
        description: "Package version"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    name: ${{ matrix.api-level }} - ${{ matrix.arch }}
    needs:
      - find-all-packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.find-all-packages.outputs.packages) }}
        config:
          - { api-level: 34, arch: x86_64, api-type-target: aosp_atd, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 33, arch: x86_64, api-type-target: aosp_atd, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 32, arch: x86_64, api-type-target: aosp_atd, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 31, arch: x86_64, api-type-target: aosp_atd, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 30, arch: x86_64, api-type-target: aosp_atd, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 29, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 29, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 28, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 28, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 27, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 27, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 26, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 26, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 25, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 25, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 24, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 24, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 23, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 23, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 22, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
#          - { api-level: 22, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
#          - { api-level: 21, arch: x86_64, api-type-target: default, host_profile: android-21-x86_64, ndk_version: 26.3.11579264 }
          - { api-level: 21, arch: x86, api-type-target: default, host_profile: android-21-x86, ndk_version: 26.3.11579264 }
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies and setuptools (required to build GLib)
        run: pip install --upgrade pip conan setuptools

      - name: install NDK
        if: startsWith(matrix.config.host_profile, 'android')
        run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ matrix.config.ndk_version }}"

      - name: conan remote
        run: conan remote add --index 0 odr https://artifactory.opendocument.app/artifactory/api/conan/conan
      - name: conan config
        run: conan config install .github/config/ubuntu-22.04/conan

      # Multiple unpublished packages in this repo have inter-dependencies
      # Can't build them until the deps are published to artifactory or at least exported
      - name: Conan export all packages
        run: python scripts/conan_export_all_packages.py

      - name: conan install
        run: conan install recipes/${{ inputs.package }}/all/conanfile.py --version ${{ inputs.version }} --build missing --profile:host ${{ matrix.config.host_profile }}
      - name: conan source
        run: conan source recipes/${{ inputs.package }}/all/conanfile.py --version ${{ inputs.version }}
      - name: conan build
        run: conan build recipes/${{ inputs.package }}/all/conanfile.py --version ${{ inputs.version }} --profile:host ${{ matrix.config.host_profile }}
      - name: conan export
        run: conan export recipes/${{ inputs.package }}/all/conanfile.py --version ${{ inputs.version }}
      - name: conan export-pkg
        run: conan export-pkg recipes/${{ inputs.package }}/all/conanfile.py --version ${{ inputs.version }} --profile:host ${{ matrix.config.host_profile }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          api-level: ${{ inputs.api-level }}
          arch: ${{ inputs.arch }}
          target: ${{ inputs.api-type-target }}
          script: |
            test_conanfile=recipes/${{ inputs.package }}/all/test_package/conanfile.py
            conan test $test_conanfile ${{ inputs.package }}/${{ inputs.version }} --build missing --profile:host ${{ matrix.config.host_profile }}
