name: android emulator test

on:
  push:
  workflow_dispatch:
    inputs:
      package_name:
        description: Package name
        type: choice
        options:
          - all
          - odrcore
          - pdf2htmlex
          - fontforge
          - poppler
          - poppler-data
          - cairo
          - openlibm
          - fontconfig
          - glib
      package_version:
        description: Package version (leave empty to build all versions)
        required: false

jobs:
  find-all-packages:
    runs-on: ubuntu-22.04
    outputs:
      packages: ${{ steps.list-packages.outputs.packages }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # Fetch whole git history.
          # Required to parse modified packages
          fetch-depth: 0

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install --upgrade pip conan

      - name: conan config
        run: conan config install .github/config/ubuntu-22.04/conan

      - name: Conan export all packages
        run: python scripts/conan_export_all_packages.py

      # Generate dependency graphs for all disjoint packages
      - run: conan graph info recipes/odrcore/all/conanfile.py --version=4.0.0 --profile:host=android-21-armv8 --format=json | tee odrcore-dependency-tree.json
        shell: bash # bash shell needed to pipefail on error
      - run: conan graph info recipes/pdf2htmlex/all/conanfile.py --version=0.18.8.rc1-20240619-git --profile:host=android-21-armv8 --format=json | tee pdf2htmlEX-dependency-tree.json
        shell: bash # bash shell needed to pipefail on error

      - name: Get requested packages from commits and workflow_dispatch inputs
        id: list-packages
        run: python scripts/list_package_versions.py
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}

  aosp_atd-target:
    if: ${{ needs.find-all-packages.outputs.packages != '[]' }}
    needs:
      - find-all-packages
#    name: ${{ matrix.api_level }} on ${{ matrix.arch }} (${{ matrix.api_type_target }})
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.find-all-packages.outputs.packages) }}
#        api_level: [34, 33, 32, 31, 30]
        api_level: [34]
        arch: [x86_64]
        api_type_target: [aosp_atd]
        include:
          - api_level: 30
            arch: x86
            api_type_target: aosp_atd
    uses: ./.github/workflows/emulator-test-inner.yml
    with:
      api_level: ${{ matrix.api_level }}
      arch: ${{ matrix.arch }}
      api_type_target: ${{ matrix.api_type_target }}
      host_profile: android-21-${{ matrix.arch }}
      ndk_version: "26.3.11579264"
      conanfile: ${{ matrix.package.conanfile }}
      test_conanfile: ${{ matrix.package.test_conanfile }}
      package_version: ${{ matrix.package.version }}
      package_reference: ${{ matrix.package.package_reference }}

  default-target:
    if: ${{ needs.find-all-packages.outputs.packages != '[]' }}
    needs:
      - find-all-packages
#    name: android-${{ matrix.api_level }} on ${{ matrix.arch }} (${{ matrix.api_type_target }})
    strategy:
      fail-fast: false
      matrix:
#        api_level: [29, 28, 27, 26, 25, 24, 23, 22, 21]
        api_level: [21]
        arch:
          - x86_64
          - x86
        api_type_target: [default]
    uses: ./.github/workflows/emulator-test-inner.yml
    with:
      api_level: ${{ matrix.api_level }}
      arch: ${{ matrix.arch }}
      api_type_target: ${{ matrix.api_type_target }}
      host_profile: android-21-${{ matrix.arch }}
      ndk_version: "26.3.11579264"
      conanfile: ${{ matrix.package.conanfile }}
      test_conanfile: ${{ matrix.package.test_conanfile }}
      package_version: ${{ matrix.package.version }}
      package_reference: ${{ matrix.package.package_reference }}
